Repository romgrk/barbar.nvim, pull requests merged in 2022-10, with the labels that each got.

#302 feat: Add new command `:BufferCloseAllButVisible`
  README.md
  doc/barbar.txt
  lua/bufferline.lua
  lua/bufferline/api.lua
Labels: request

#307 ref(state): use `vim.deprecate` if possible
  lua/bufferline/state.lua
Labels: request

#305 fix: buffer close animations
  lua/bufferline/jump_mode.lua
  lua/bufferline/options.lua
  lua/bufferline/render.lua
  lua/bufferline/state.lua
Labels: bug

#308 perf(bbye): use `vim.cmd.bdelete` on Neovim 0.8+
  lua/bufferline.lua
  lua/bufferline/bbye.lua
Labels: request

#311 fix(bbye): `BufferCloseAll*` commands
  lua/bufferline/bbye.lua
Labels: bug

#309 fix: assuming file icon is single char width
  lua/bufferline/icons.lua
  lua/bufferline/layout.lua
  lua/bufferline/render.lua
  lua/bufferline/state.lua
Labels: bug

#313 fix: incorrectly handled negative :BufferGoto index
  lua/bufferline/api.lua
Labels: bug

#314 redraw tabline when render.update
  lua/bufferline/render.lua
Labels: bug, upstream

#316 fix(render): nvim-session-manager incompatability
  lua/bufferline/render.lua
Labels: bug

#298 feat: hide buffers
  README.md
  doc/barbar.txt
  lua/bufferline/api.lua
  lua/bufferline/buffer.lua
  lua/bufferline/layout.lua
  lua/bufferline/options.lua
  lua/bufferline/render.lua
Labels: request

#318 fix(state): offset text can be `nil`
  lua/bufferline/state.lua
Labels: bug, documentation

#324 fix(render): no file names after loading session
  lua/bufferline/render.lua
Labels: bug

#327 fix(buffer): multi-code-point chars cut off
  lua/bufferline/buffer.lua
Labels: bug
