Repository romgrk/barbar.nvim, pull requests merged in 2022-12, with the labels that each got.

#334 feat: show diagnostic symbols in bufferline
  README.md
  doc/barbar.txt
  lua/bufferline/api.lua
  lua/bufferline/buffer.lua
  lua/bufferline/highlight.lua
  lua/bufferline/jump_mode.lua
  lua/bufferline/layout.lua
  lua/bufferline/options.lua
  lua/bufferline/render.lua
  lua/bufferline/state.lua
  lua/bufferline/utils.lua
Labels: request

#337 fix(buffer): no_name_title option
  lua/bufferline/buffer.lua
Labels: bug

#335 feat: highlight alternate buffer
  README.md
  doc/barbar.txt
  lua/bufferline/buffer.lua
  lua/bufferline/highlight.lua
  lua/bufferline/options.lua
  lua/bufferline/render.lua
Labels: request

#338 fix(render): scroll animates when animation disabled
  lua/bufferline/render.lua
Labels: bug

#341 fix(api): `BufferCloseAllButVisible` not closing alternate buffers
  lua/bufferline/api.lua
Labels: bug

#343 perf: c8f972dbab8d90d340cf6e840b73cddc12c350b2
  lua/bufferline/api.lua
  lua/bufferline/buffer.lua
  lua/bufferline/render.lua
Labels: perf

#344 fix: `buffer_numbers` not accounted for in `layout`
  lua/bufferline/layout.lua
  lua/bufferline/options.lua
  lua/bufferline/render.lua
Labels: bug

#339 feat: `BufferPickDelete` command
  lua/bufferline.lua
  lua/bufferline/api.lua
Labels: request

#349 ref(render): deduplicate checks for `icons` options
  lua/bufferline/render.lua
Labels: refactor
