Repository romgrk/barbar.nvim, pull requests merged in 2022-11, with the labels that each got.

#331 Compatibility issue with Lua5.1
  lua/bufferline/render.lua
  lua/bufferline/state.lua
Labels: bug, upstream

#333 docs(README): update `nvim-web-devicons` repo link
  README.md
Labels: documentation

#317 feat: option to exclude file extensions from buffer name
  README.md
  doc/barbar.txt
  lua/bufferline/buffer.lua
  lua/bufferline/icons.lua
  lua/bufferline/layout.lua
  lua/bufferline/options.lua
  lua/bufferline/render.lua
  lua/bufferline/state.lua
  lua/bufferline/utils.lua
Labels: request

#285 Add BufferMoveStart command
  lua/bufferline.lua
Labels: request
