Repository romgrk/barbar.nvim, pull requests merged in 2023-04, with the labels that each got.

#420 fix(render): ellipsis changes layout
  lua/barbar/render.lua
Labels: bug

#395 feat: `sidebar_filetypes`
  README.md
  doc/barbar.txt
  lua/barbar.lua
  lua/barbar/api.lua
  lua/barbar/config.lua
  lua/barbar/events.lua
  lua/barbar/layout.lua
  lua/barbar/render.lua
  lua/barbar/state.lua
  lua/barbar/utils.lua
Labels: request

#422 chore: editorconfig
  .editorconfig
  doc/barbar.txt
Labels: chore

#423 chore(editorconfig): preserve final newline
  .editorconfig
Labels: chore

#424 docs(README): filetree integration feature
  README.md
Labels: documentation

#425 docs(README): remove broken ToC links
  README.md
Labels: documentation

#418 fix: animations
  lua/barbar/animate.lua
  lua/barbar/fs.lua
  lua/barbar/layout.lua
  lua/barbar/render.lua
  lua/barbar/state.lua
Labels: bug, refactor

#436 fix: typo custom_color -> custom_colors
  lua/barbar/config.lua
  lua/barbar/render.lua
Labels: bug

#437 docs(config): deprecation warning suggests non-existant option
  lua/barbar/config.lua
Labels: bug

#434 docs(README): we don't support `netrw`
  README.md
Labels: documentation

#439 chore(editorconfig): add emmylua settings
  .editorconfig
Labels: chore

#440 fix: `:BufferPick` invalid char
  .editorconfig
  lua/barbar/api.lua
Labels: bug

#438 feat: disable auto-setup
  README.md
  doc/barbar.txt
  lua/barbar/config.lua
  plugin/barbar.lua
Labels: request

#408 feat: pinned buffers stay visible
  README.md
  doc/barbar.txt
  lua/barbar/api.lua
  lua/barbar/bbye.lua
  lua/barbar/buffer.lua
  lua/barbar/config.lua
  lua/barbar/events.lua
  lua/barbar/layout.lua
  lua/barbar/render.lua
  lua/barbar/state.lua
  lua/barbar/utils.lua
Labels: request

#443 Refactor and more
  lua/barbar/api.lua
  lua/barbar/config.lua
  lua/barbar/groups.lua
  lua/barbar/highlight.lua
  lua/barbar/layout.lua
  lua/barbar/render.lua
Labels: request, refactor

#444 fix: typos
  README.md
  autoload/bufferline.vim
  doc/barbar.txt
  lua/barbar/events.lua
  lua/barbar/highlight.lua
Labels: bug, documentation

#448 fix(buffer): buffer name cut off at `<e2>`
  lua/barbar/buffer.lua
Labels: bug

#450 fix: close click confirmation message reports error
  lua/barbar/bbye.lua
  lua/barbar/events.lua
Labels: bug

#445 perf: misc
  lua/barbar/config.lua
  lua/barbar/render.lua
Labels: perf

#452 fix(render): padding uses `Sign` hl group
  lua/barbar/render.lua
Labels: bug

#446 ref: `local m` → `local groups`
  autoload/bufferline.vim
  lua/barbar.lua
  lua/barbar/api.lua
  lua/barbar/events.lua
  lua/barbar/groups.lua
  lua/barbar/ui/layout.lua
  lua/barbar/ui/nodes.lua
  lua/barbar/ui/render.lua
  lua/barbar/ui/types.lua
  lua/bufferline/layout.lua
  lua/bufferline/render.lua
Labels: documentation, refactor

#456 docs: session integration
  README.md
  doc/barbar.txt
  lua/barbar/state.lua
Labels: documentation

#459 fix(layout): attempt to calculate width of invalid buffer
  lua/barbar/ui/layout.lua
Labels: bug

#463 feat: add ability to display optional git status indicators
  README.md
  doc/barbar.txt
  lua/barbar/buffer.lua
  lua/barbar/config.lua
  lua/barbar/events.lua
  lua/barbar/highlight.lua
  lua/barbar/ui/layout.lua
  lua/barbar/ui/render.lua
Labels: request

#451 ref: granularize imports
  lua/barbar.lua
  lua/barbar/animate.lua
  lua/barbar/api.lua
  lua/barbar/bbye.lua
  lua/barbar/buffer.lua
  lua/barbar/config.lua
  lua/barbar/events.lua
  lua/barbar/fs.lua
  lua/barbar/highlight.lua
  lua/barbar/icons.lua
  lua/barbar/jump_mode.lua
  lua/barbar/state.lua
  lua/barbar/types.lua
  lua/barbar/ui/layout.lua
  lua/barbar/ui/nodes.lua
  lua/barbar/ui/render.lua
  lua/barbar/ui/types.lua
  lua/barbar/utils.lua
  lua/barbar/utils/highlight.lua
  lua/barbar/utils/list.lua
  lua/barbar/utils/table.lua
  lua/bufferline.lua
  lua/bufferline/animate.lua
  lua/bufferline/api.lua
  lua/bufferline/bbye.lua
  lua/bufferline/buffer.lua
  lua/bufferline/config.lua
  lua/bufferline/events.lua
  lua/bufferline/highlight.lua
  lua/bufferline/icons.lua
  lua/bufferline/jump_mode.lua
  lua/bufferline/layout.lua
  lua/bufferline/render.lua
  lua/bufferline/state.lua
  lua/bufferline/utils.lua
  plugin/barbar.lua
Labels: refactor

#468 perf: track git and diagnostics in `state`
  lua/barbar/buffer.lua
  lua/barbar/config.lua
  lua/barbar/events.lua
  lua/barbar/state.lua
  lua/barbar/ui/layout.lua
  lua/barbar/ui/render.lua
Labels: perf

#469 docs: `sidebar_filetypes` limitation
  README.md
Labels: documentation

#470 docs(barbar.txt): `git` → `gitsigns`
  doc/barbar.txt
Labels: documentation

#471 docs(README): document install requirements up front
  README.md
Labels: documentation

#409 feat: add number styling
  README.md
  doc/barbar.txt
  lua/barbar/config.lua
  lua/barbar/state.lua
  lua/barbar/ui/render.lua
Labels: request

#472 fix(events): git status not loading on vim start
  lua/barbar/events.lua
Labels: bug

#473 fix(render): pinned buffers
  lua/barbar/ui/render.lua
Labels: bug

#474 fix: use `bufnr()` when loading session
  lua/barbar/events.lua
  lua/barbar/state.lua
Labels: bug

#476 fix
  lua/barbar/ui/render.lua
Labels: bug
