Repository romgrk/barbar.nvim, pull requests merged in 2023-05, with the labels that each got.

#483 fix(icons): check for `get_icons` returning `nil`
  lua/barbar/icons.lua
Labels: bug

#485 feat: `Buffer<Activity>SignRight` highlight
  README.md
  doc/barbar.txt
  lua/barbar/highlight.lua
  lua/barbar/ui/render.lua
Labels: request

#484 feat: `focus_on_close = 'previous'`
  README.md
  doc/barbar.txt
  lua/barbar/bbye.lua
  lua/barbar/config.lua
Labels: request

#488 ref(render): scroll to fill tabline when closing a buffer
  lua/barbar/ui/render.lua
Labels: refactor

#490 fix(events): attempt to operate on invalid buffer
  lua/barbar/events.lua
Labels: bug

#486 feat: `icons.preset`
  README.md
  doc/barbar.txt
  lua/barbar/config.lua
  lua/barbar/events.lua
  lua/barbar/highlight.lua
  lua/barbar/utils/highlight.lua
Labels: request

#496 ref(highlight): make `Arrow` and `Tabpages` default hl more semantic
  lua/barbar/highlight.lua
  lua/barbar/ui/render.lua
Labels: refactor

#495 feat: provide count of buffers to pick delete
  lua/barbar.lua
  lua/barbar/api.lua
Labels: request

#500 fix(highlight): `BufferTabpageFill` highlight changed
  lua/barbar/highlight.lua
Labels: bug

#503 fix(events.lua): Listen for default and user-configured sidebar_filetype close events
  lua/barbar/events.lua
Labels: bug
